### ISSUE TITLE
Get document / supply a document deserializer

### ISSUE THREAD

**Issue by megamidge** [kazuooooo/pinia-plugin-firestore-sync#2]
This is a feature request.

It would be handy if either:
 - The API synced the ID of each document a long with it's data. Ideally as a non-enumerable property.
 OR
 - Allow a deserializer to be passed. Would be a function that is passed the snapshot, and returns the data to put into the store.
 
May have a look at integrating the first option if I find some time.

**Comment by megamidge** [comment]
I've addressed the first bullet point #3.

**Comment by kazuooooo** [comment]
@megamidge 
I've released [v1.1.0](https://www.npmjs.com/package/pinia-plugin-firestore-sync) thank you for your cooperation🥰
