### ISSUE TITLE
Deleted fields are not propagated for DocumentReferences.

### ISSUE THREAD

**Issue by megamidge** [kazuooooo/pinia-plugin-firestore-sync#5]
If a single firestore document is listened to, if fields of that document are entirely removed, these changes are not reflected back onto the state.
The reason appears to be because `store.$patch({ [key]: data })` in effect merges the new data onto the existing data - meaning newly undefined fields are unaffected.

It's important to note that the same issue doesn't occur for collections because the entire key in the state is replaced.

I'm proposing that the same is done for DocumentReference.
Instead of:
`store.$patch({ [key]: data })`
Do: 
`store.$patch((state) => {
            state[key] = data
          })`

I will be submitting a merge request soon to address this. Ran a few tests and behaviour with regards to reactivity appears to be identical.

**Comment by kazuooooo** [comment]
@megamidge 
Sorry for being late.
Thank you!
I'm looking forward to your PR.

**Comment by megamidge** [comment]
@kazuooooo no worries, I've been meaning to get around to this, super easy. See #8. Probably worth getting round to minimising the duplicate code as the query/collection vs data syncing is _almost_ identical now.

**Comment by kazuooooo** [comment]
@megamidge 
I released [v1.2.0](https://github.com/kazuooooo/pinia-plugin-firestore-sync/releases/tag/1.2.0).
Thank you for your contribution🥰
